/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElText: typeof import('element-plus/es')['ElText']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    MainMenuV2: typeof import('./src/components/menu/MainMenuV2.vue')['default']
    MainMenuV2Item: typeof import('./src/components/menu/MainMenuV2Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
